force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Instance__c/Survey_Instance__c.object-meta.xml
<CustomObject>
    <label>Survey Instance</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Instances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey_Instance__c/fields/Available_Until__c.field-meta.xml
<CustomField>
    <fullName>Available_Until__c</fullName>
    <label>Available Until</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Survey_Instance__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Survey Instances</relationshipLabel>
    <relationshipName>Survey_Instances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/tinyKudos/Survey/SurveyController.cls
public class SurveyController {
    @TestVisible private static ISurveyRepository repository;

    @AuraEnabled(Cacheable=true)
    public static SurveyDto getSurvey() {
        try {
            // Get the survey from the database. If it doesn't exist, return null.
            List<Survey__c> surveys = [
                SELECT
                    Id,
                    Name,
                    (
                        SELECT Id, Name, Title__c, Description__c
                        FROM Questions__r
                    ),
                    (
                        SELECT Available_Until__c
                        FROM Survey_Instances__r
                        WHERE Available_Until__c >= :Date.today()
                    )
                FROM Survey__c
            ];
            if (surveys.isEmpty()) {
                throw new DataException(
                    'No surveys found'
                );
            }
            for (Survey__c survey : surveys) {
                if (survey.Survey_Instances__r.isEmpty()) {
                    throw new DataException(
                        'No available survey instances found'
                    );
                }
            }
            return new SurveyDto(surveys[0]);
        } catch (Exception e) {
            String errorMessage = 'Unable to retrieve the requested survey';
            AuraHandledException error = new AuraHandledException(errorMessage);
            error.setMessage(errorMessage + ' : ' + e.getMessage());
            throw error;
        }
    }

    public class DataException extends Exception { }
}