force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Display_Name__c</fullName>
    <label>Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/tinyKudos/Survey/SurveyControllerTest.cls
@IsTest
private class SurveyControllerTest {
    @IsTest
    static void getSurvey_surveyWithQuestionsConfigured_getDataBack() {
        ISurveyRepository surveyRepository = new TestSurveyRepository();

        SurveyController.repository = surveyRepository;

        SurveyDto result = SurveyController.getSurvey();

        Assert.areNotEqual(null, result);
    }

    private class TestSurveyRepository implements ISurveyRepository {
        public List<SurveyDto> getSurveysWithinRange() {
            Survey__c record = new Survey__c(
                Display_Name__c = 'Test Survey',
                Start_Date__c = Date.today()
            );

            return new List<SurveyDto> {};
        }
    }


    // TODO: get rid of if I don't want it
    private static void gettingThisOutOfHere() {
        Survey__c testSurvey = new Survey__c(
            Display_Name__c = 'Test Survey',
            Start_Date__c = Date.today()
        );
        insert testSurvey;

        Question__c testQuestion = new Question__c(
            Survey__c = testSurvey.Id
        );
        insert testQuestion;
    }

    // Getting the survey when there is a survey configured with questions for today's date -> Happy Path
    // Expect: to get the survey with the question

    // -----------------------------
    // Getting the survey when there is a survey configured with questions for outside of date range
    // Getting the survey when there is no survey configured
    // Getting survey with no questions configured
}