force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Survey__c.field-meta.xml
<CustomField>
    <fullName>Survey__c</fullName>
    <label>Survey</label>
    <referenceTo>Survey__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/tinyKudos/Survey/SurveyDto.cls
public class SurveyDto {
    @AuraEnabled
    public Id recordId { get; set; }

    @AuraEnabled
    public List<QuestionDto> questions { get; set; }

    public SurveyDto(Survey__c surveyRecord) {
        this.recordId = surveyRecord.Id;

        this.questions = new List<QuestionDto>();
        if (!surveyRecord.Questions__r.isEmpty()) {
            for (Question__c question : surveyRecord.Questions__r) {
                this.questions.add(new QuestionDto(question));
            }
        }
    }
}